// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPjHAgo6Op-eqcRGrtex5Ivsad7JM8iso',
    appId: '1:63078663839:web:89a45b43686c5b93b1c4aa',
    messagingSenderId: '63078663839',
    projectId: 'counter-app-482e9',
    authDomain: 'counter-app-482e9.firebaseapp.com',
    storageBucket: 'counter-app-482e9.appspot.com',
    measurementId: 'G-8QLWR0L8E8',
    // databaseURL: 'https://counter-app-482e9-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsurcNHA5Zp0SEgUmgmuKfiBg09BCFBk',
    appId: '1:63078663839:android:3d19dee70572a21db1c4aa',
    messagingSenderId: '63078663839',
    projectId: 'counter-app-482e9',
    storageBucket: 'counter-app-482e9.appspot.com',
    // databaseURL: 'https://counter-app-482e9-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeXYvdlxe7vnxtPFWuZI6oGJNU3GHGdkU',
    appId: '1:63078663839:ios:7c129f223103da1db1c4aa',
    messagingSenderId: '63078663839',
    projectId: 'counter-app-482e9',
    storageBucket: 'counter-app-482e9.appspot.com',
    iosClientId:
        '63078663839-dtt25rf77g1tjb7epmdq5725mqrk666g.apps.googleusercontent.com',
    iosBundleId: 'com.counter.app',
    // databaseURL: 'https://counter-app-482e9-default-rtdb.firebaseio.com/',
  );
}
